### ISSUE TITLE
Docker installation failure

### ISSUE THREAD

**Issue by rudy1976s** [mixerapi/demo#19]
Hello there
I was trying to install the docker but I encountered the following error:

`18.79 configure: error: rtnetlink.h is required, install the linux-headers package: apk add --update linux-headers
18.80 ERROR: `/tmp/pear/temp/xdebug/configure --with-php-config=/usr/local/bin/php-config' failed
------
failed to solve: process "/bin/sh -c if [[ \"$ENV\" != \"prod\" ]]; then     apk add git     && apk add --no-cache --virtual .php-deps file re2c autoconf make zlib zlib-dev g++ curl     && pecl install xdebug     && docker-php-ext-enable xdebug     && apk del -f .php-deps     ; fi" did not complete successfully: exit code: 1
make: *** [Makefile:110: init] Error 17`

Could you please address me to correct the error ?

Thanks in advance

Rudy

**Comment by cnizzardini** [comment]
I think an additional dependency became required in there. I recall resolving this in one of my applications, perhaps this:

`apk add --update --no-cache --virtual .php-deps file re2c autoconf make zlib zlib-dev g++ curl linux-headers`

I think linux headers for some reason is required now. I will look at this more in a bit.

**Comment by rudy1976s** [comment]
Sorry if I change topic there but I don't know how to contact you directly: do you offer support for mixerapi integration ? I have several problem implementing it on a project based on plugins

**Comment by cnizzardini** [comment]
^ Create issues for those issues @rudy1976s

**Comment by cnizzardini** [comment]
This branch works now https://github.com/mixerapi/demo/tree/fix-demo

The outstanding issue is something to do with authentication in the admin plugin. I'll have to step through that when I have more time :-/

**Comment by rudy1976s** [comment]
Hello Chris
I have tried to clone the repo again and I got the following
![Screenshot 2023-12-06 084812](https://github.com/mixerapi/demo/assets/1161343/538c0882-dd05-4289-a7e8-13dee409d0df)

**Comment by cnizzardini** [comment]
What operating system and version of docker are you on? Also can you post text and not screenshots when possible.

**Comment by cnizzardini** [comment]
For me, the demo works now.
